server:
  port: 9094

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ahmet
    password: "020900"
    url: jdbc:postgresql://pazarlama-test-postgres-db:5432/companydb_rituelpazarlama

  # Redis için doğru konum: spring.data.redis.*
  data:
    redis:
      host: pazarlama-test-redis-cache
      port: 6379
      password: "1alexdegil41*?"

  jpa:
    # tercih: spring.jpa.hibernate.ddl-auto (daha sık kullanılır)
    hibernate:
      ddl-auto: update
    # explicit dialect belirtmek Hibernate'in "Unable to determine Dialect" hatasını çözer
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    # alternatif tek satır
    # database-platform: org.hibernate.dialect.PostgreSQLDialect

  elasticsearch:
    uris: http://pazarlama-test-elasticsearch:9200

jwt:
  secret: b85ad78baba523b5c1d307c5bf9b96ac1d5c099f56787539f9a2ed3aae
  expiration: 3600000
  refresh-token:
    expiration-ms: 1209600000

gcp:
  project-id: fabled-web-466708-s2
  bucket-name: rituelx_pazarlama_documents_bucket
  credentials-location: classpath:gcs-key.json

external:
  service:
    url:
      log-uri: ${LOG_SERVICE_CLIENT_URI}
      user-profile-uri: ${USER_PROFILE_SERVICE_CLIENT_URI}
