server:
  port: 9093

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ahmet
    password: 020900
    url: jdbc:postgresql://pazarlama-test-postgres-db:5432/user_profiledb_rituelpazarlama
  data:
    redis:
      host: pazarlama-test-redis-cache
      port: 6379
      password: "1alexdegil41*?"

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: b85ad78baba523b5c1d307c5bf9b96ac1d5c099f56787539f9a2ed3aae
  expiration: 3600000
  refresh-token:
    expiration-ms: 1209600000

cloudinary:
  api-key: 141285467799214
  api-secret: NiULcQawF6EyMaBh4lcxKmhqTTk
